### ISSUE TITLE
release 0.1.3

### ISSUE THREAD

**Issue by thepian** [socketstream/ss-sockjs#4]
latest sockjs and a license

**Comment by paulbjensen** [comment]
Hi, is there a PR for this?

**Comment by paulbjensen** [comment]
Ah, I see master was updated, ignore me.

**Comment by paulbjensen** [comment]
I don't have npm publish access rights, will try and resolve.

**Comment by paulbjensen** [comment]
Resolved npm access rights, and published 0.1.3
